MITLibraries/carbon

carbon/__init__.py
carbon/app.py
carbon/cli.py
requirements.txt
tests/conftest.py
tests/test_app.py
tests/test_cli.py

This adds the framework for generating an XML feed of the person
data. We'll need to figure out the mapping for several of the fields
in order to complete the record XML.

Generate XML feed from person data

---

carbon/app.py
carbon/cli.py
requirements.txt
setup.py
tests/conftest.py
tests/test_app.py
tests/test_cli.py
tox.ini

This adds a command line option to POST the XML feed to a URL. This
also ensures that UTF-8 encoding is used throughout when serializing
the XML.

Add option to post data to URL

---

README.rst
carbon/__init__.py
carbon/app.py
carbon/cli.py
requirements.txt
tests/test_app.py
tests/test_cli.py

This changes the XML generation to stream the output rather than
building the feed entirely in memory first. This also removes the
functionality to POST the feed. Since the feed can be saved to a
file or piped elsewhere, other tools, such as curl, can cover this.

Use streaming XML generator

---

.gitignore
carbon/app.py
carbon/cli.py
lambda.py

This adds a Lambda handler function. There are a few assumptions being
made here. This assumes the Lambda will be triggered by a CloudWatch
event and that the event will pass a JSON structure that indicates the
type of feed to generate. The function is configured through environment
variables. Env vars that contain sensitive information should be added
to an AWS Secrets object.
I'm making some guesses here as to how the event data and secrets get
passed to the Lambda. The documentation suggests it's possible to pass
JSON in both cases, but it's not entirely clear. Some adjustment may be
required after attempting to run this in AWS.

Add support for running as AWS Lambda

---

.travis.yml
carbon/__init__.py
carbon/app.py
carbon/db.py
tests/conftest.py
tests/test_app.py
tox.ini

Closes #40. This adds a tox environment for flake8 and a corresponding
entry to the travis test matrix. Also fixes all the flake8 errors.

Add flake8 to test suite

---

README.rst

This adds documentation about setting the required environment variables
and configuring the CloudWatch event data.

Add docs for configuring Lambda

---

README.rst
carbon/app.py
lambda.py

It turns out the easiest way to handle this with the tools we have
available is to pass some of the environment variables to the function
through the Cloudwatch event object. Both env vars and the event object
can be used, with the event object taking precedence.

Use Lambda event object to set env vars

---

README.rst
build.sh
publish.sh

This changes the name of the Lambda deployment package to always be
`carbon.zip`. We don't currently have the infrastructure to handle
changing Lambda aliases so we'll just overwrite the existing Lambda and
let the two week delay in staging/prod cron schedules highlight any
issues. Downgrading the Lambda to an older version can be done manually
using the deployment instructions in the README.

Update Lambda publishing step

---

.gitignore
.travis.yml
Dockerfile
Makefile
Pipfile
Pipfile.lock
README.rst
carbon/__init__.py
setup.py
tests/test_cli.py
tox.ini

This PR abandons Lambda for Fargate. The app itself has not changed aside from a different versioning scheme. The makefile has been updated to handle most of the build process. If you want to see the changes, make sure your aws cli credentials are configured and run:
```
$ make clean
$ make dist
$ docker run --rm carbon:latest
```
This should output the usage message for carbon.

Containerize carbon

---

Makefile

The $ has to be escaped in the makefile, otherwise the push will fail
with a 403.

Escape the aws cli docker login

---

Makefile

This adds a default target that will print a help message for the
Makefile.

Add Makefile help

---

Makefile
carbon/app.py
carbon/cli.py
tests/test_cli.py

This adds a few pieces to make carbon work on Fargate. The main change
is to add SNS notification directly into the app. Cloudwatch logging
from the container's stdout is a little flakey. The build process will
now publish the container to both the stage and prod ECR repos. With
real CI/CD we'd just publish to stage, but with Travis this is the best
we can do.

Add Fargate functionality

---

carbon/app.py

By default there is no timeout. This adds a 30 second timeout.

Add timeout to FTP connection

---

carbon/app.py
tests/conftest.py
tests/fixtures/data.yml

We ran into a case where an individual does not have a start date which
caused the upload to fail. My documentation tells me that this field is
not required for the Elements feed, so the solution here is to just omit
the field when the data is not available.

Add check for existence of arrive date

---

carbon/app.py
tests/conftest.py
tests/fixtures/data.yml

If someone is missing a start date we need to skip them altogether. This
backs out the last commit and filters out people at the query level.
We have only encountered a single instance of someone missing a start
date so my assumption is that this is just a data error in some upstream
system.

Skip people without an arrive date

---

Makefile
README.rst

This updates the documents for the current Fargate deployment process.
The Makefile has also been modified to account for the production
deployment. Actually promoting the staging build to production will
require (minimal) manual intervention.

Update docs and Makefile to reflect Fargate deploy

---

.travis.yml
Makefile
Pipfile.lock

This switches to using the shared deploy bucket and adds a job during the test stage in Travis to check that the container builds successfully.
Dependencies have been updated as well to address an incompatible version mismatch between awscli and botocore.

Use shared deploy bucket

---

Makefile

* Update the environment variable definitions in the Makefile
The previous Makefile had a hardcoded name for an S3 bucket that holds a copy of the Oracle library .zip file. This makes that S3 bucket name dynamic to match the dev/stage/prod account from which it should be pulled.
* https://mitlibraries.atlassian.net/browse/IN-615
The problem was discovered in the failure of the [stage-deploy workflow run](https://github.com/MITLibraries/carbon/actions/runs/3331238125/jobs/5511040163#step:7:60). The wrong S3 bucket was being accessed.
To test this, checkout this branch locally, authenticate to AWS Dev1 account and run
```bash
make distclean
make deps
```
and you should see the .zip file get downloaded from the Dev1 S3 bucket.  Then, authenticate to AWS Stage-Workloads account and run …

Fix for Oracle ZIP Location

---

Makefile
README.md
carbon/app.py
carbon/cli.py
tests/conftest.py
tests/test_cli.py
tests/test_config.py

Refactor Carbon app to use new Symplectic FTP SSM parameters
Prior to these updates, the Carbon app relied on three (3) separate SSM parameters 
related to Symplectic Elements FTP credentials: 
* `/tfvars/apps-vars/carbon/ftp-host`;
* `/tfvars/apps-vars/carbon/ftp-pass`; and
* `/tfvars/apps-vars/carbon/ftp-user`
To simplify management of FTP credentials, FTP credentials are now stored
in a one (1) SSM parameter that consists of a single JSON formatted string.
Eventually, the deprecated SSM parameters should be removed to avoid confusion.
Also, @ehanson8 , I added a note about the minor issue related to the CLI test `test_cli_connection_tests_fail` in the `README`; figured it'd be easier to keep track off than the commit!
1. Review Cloudwatch …

IN-887 Refactor Carbon app to use new Symplectic FTP parameters

---

README.md
carbon/app.py
carbon/cli.py
carbon/database.py
tests/conftest.py
tests/test_app.py
tests/test_cli.py

Restructure the application codebase to include the creation of the SQLAlchemy engine as part of the main workflow.
1. Clone the repo.
2. Check into this branch `IN-906-include-engine-creation-in-main`.
3. Create a new virtual environment.
4. Install dependencies: `make install`.
5. Run linters: `make lint`.
6. Run test: `make test`.
All tests should pass as a result of making updates to necessary classes and methods in `app.py` to accept an instance of `DatabaseEngine`. 
NO
(not just this pull request message)

IN-906 Include creation of SQLAlchemy engine in main workflow

---

carbon/app.py
carbon/feed.py
tests/conftest.py
tests/test_app.py
tests/test_helpers.py

Introduce a module (`feed.py`) containing classes for creating 
two types of XML feeds--`PeopleXmlFeed` and `ArticlesXmlFeed` to improve code coherency. 
Encapsulating the previously 'loose' functions in `app.py` into these two classes results in
cleaner and more readable code, which will make it easier for future developers to maintain 
and/or introduce new features to the Carbon application.
* `feed.py` Consists of a 'base' XML feed class that is used by the `PeopleXmlFeed' and `ArticlesXmlFeed` subclasses.
1. Clone the repo.
2. Check into this branch `IN-907-define-feed-classes`.
3. Create a new virtual environment.
4. Install dependencies: `make install`.
5. Run linters: `make lint`.
6. Run test: `make test`.
All tests should pass, and since `carbon.app.FileWriter` and all `pytest` …

IN-907 Define classes for XML feeds

---

Makefile
README.md
carbon/app.py
carbon/cli.py
carbon/config.py
carbon/helpers.py
tests/conftest.py
tests/test_cli.py
tests/test_helpers.py

Scope out a workflow that allows a developer to easily test the application.
When testing, the main quirk is that the host name for the Data Warehouse is different when you connect to the Data Warehouse **outside of AWS**. Please reach out to me if you need help setting you `.env` file.
Follow the instructions in the README to run the Data Warehouse connection test
by **running the application in a Docker container on your local machine**. 
1. Follow the instructions in the README under "Running the application on your local machine"
2. Follow the instructions in the README under "With Docker".
3. Run `make run-connection-tests-dev`. 
NO
(not just this pull request message)

In 908 build dev testing framework

---

Makefile
carbon/app.py
carbon/database.py
tests/test_cli.py

A few sentences describing the overall goals of the pull request's commits.
Why are we making these changes? Is there more work to be done to fully
achieve these goals?
For **IN-923 Raise exceptions for failed connection tests**:
1. Check the CloudWatch for successful connection tests: [log](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/carbon-ecs-stage/log-events/carbon$252Fcarbon-ecs-stage$252F93b0a7baafbd41c4936a379277698054)
* To produce this log, I ran the Docker image with the code as-is, which should run successfully as it uses the appropriate credentials and  does not include a forced `ZeroDivisionError`.
2. Check the CloudWatch log for failed connection test for Data Warehouse (tests [lines …

IN-923 Raise exceptions for failed connection tests / IN-925 Add Makefile commands to run Carbon feeds

---

README.md
carbon/app.py
carbon/cli.py
carbon/feed.py

The work in this PR is to investigate the 'errors' with the `ftplib.storbinary` method that are logged for the 'people' feed (described in [this Github issue](https://github.com/MITLibraries/carbon/issues/112)) and the 'articles' feed (described in [this Jira ticket](https://mitlibraries.atlassian.net/browse/IN-878)]. 
Here are some key learnings from this effort: 
* **Articles feed**
* It seems the error may be due to the FTP connection 'hanging' because as `storbinary()` is running (it takes >5 minutes for the Article, it is 'blocking' any other commands from being run on the FTP server. This leads to an 'idle' FTP connection. As described in [this thread](https://stackoverflow.com/questions/19692739/python-ftplib-hangs-at-end-of-transfer): 
> Either your client is timing out the …

In 924 fix ftp file transfer method

---

.dockerignore
Pipfile.lock
carbon/app.py
carbon/cli.py
carbon/config.py
carbon/database.py
carbon/helpers.py
tests/conftest.py
tests/test_cli.py
tests/test_config.py
tests/test_helpers.py

Refactor config module to use a `Config` class to improve code readability and flow.
The CLI `main()` method was also updated to exit cleanly in the event of failed
connection tests.
* **Updating the CLI `main()` method**
* During testing, it was discovered that the `Traceback` was printing twice in the CloudWatch logs.
* In order to address this issue, the following updates were made: 
* Wrap each connection test in a `try-except` block;
* Moving the wrapped code into a function in `carbon.app.run_all_connection_tests()` to keep `cli.py` 
organized.
* I debugged a couple of errors with @ghukill and he suggested that "logging.exception [may] not [be] needed for an understood exception like `oracledb.exceptions.DatabaseError: ORA-12170: TNS:Connect timeout occurred`" and posted that …

IN-928 Restructure the config module to use a 'Config' class

---

README.md

Create a data flow diagram for the Carbon application.
I went back-and-forth on what type of diagram to use (flowchart, sequence, or state flow), but ultimately, I decided that this flow chart showing **where the data comes from and where it ends up** were the key questions a data engineer might ask when first working on the application. I couldn't figure out a diagram type--with the existing `mermaid` features--that could easily communicate the 'threading' component of the Carbon application, so i opted to just create this diagram for now. However, I'd be happy to get suggestions for future work!
A little while ago, I made this diagram on Figma that tries to show the concurrent threads (i.e., green bars are used to indicate which thread is running for a given action), but I couldn't see …

IN-930 Create data flow diagram
